### ISSUE TITLE
Android: Pointer on elevation graph

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-elevation#270]
Hi Raruto,

the pointer goes over the edge on the left in elevation graph  on android:

https://github.com/Raruto/leaflet-elevation/assets/73023225/93c082de-a830-490a-bd30-de8a89aaa654

The video is from Chrome, but in Firefox it is also.

Thank you very much.

**Comment by Raruto** [comment]
Hi Hupe,

You can also get the same error from Chrome Desktop's [mobile emulator](https://developer.chrome.com/docs/devtools/device-mode/).

```
Uncaught TypeError: s(...).moved is not a function
    at SVGGElement.d (d3.min.js:2:68094)
    at SVGGElement.<anonymous> (d3.min.js:2:20668)
d @ d3.min.js:2
(anonymous) @ d3.min.js:2
```

It's probably a problem related to touch devices (perhaps a recent browser update?)

![image](https://github.com/Raruto/leaflet-elevation/assets/9614886/9a22b0f8-341a-4905-9883-44903a53787f)

👋 Raruto

**Comment by Raruto** [comment]
Same as: https://github.com/d3/d3-brush/issues/83
